---
title: Suitable Impressive Thesis Title
author: Maximilian Maigler
institute: Institut für Physik and Plasma Technologie
degree: Dr.-Ing.
author-includes: |
  \renewcommand{\vec}[1]{\mathbf{#1}}
  \usepackage{siunitx}
  \sisetup{
    detect-weight=true,
    detect-family=true,
    range-phrase={-},
    exponent-product={\cdot},
    range-units=single,
    detect-all=true
  }
abstract: |
  Your abstract text goes here.  Check your departmental regulations, but generally this should be less than 300 words.
  See the beginning of Chapter \ref{ch:2-litreview} for more. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  Pellentesque sit amet nibh volutpat, scelerisque nibh a, vehicula neque. Integer placerat nulla massa, et vestibulum
  velit dignissim id. Ut eget nisi elementum, consectetur nibh in, condimentum velit. Quisque sodales dui ut tempus
  mattis. Duis malesuada arcu at ligula egestas egestas. Phasellus interdum odio at sapien fringilla scelerisque. Mauris
  sagittis eleifend sapien, sit amet laoreet felis mollis quis. Pellentesque dui ante, finibus eget blandit sit amet,
  tincidunt eu neque. Vivamus rutrum dapibus ligula, ut imperdiet lectus tincidunt ac. Pellentesque ac lorem sed diam
  egestas lobortis.  Suspendisse leo purus, efficitur mattis urna a, maximus molestie nisl. Aenean porta semper tortor a
  vestibulum. Suspendisse viverra facilisis lorem, non pretium erat lacinia a. Vestibulum tempus, quam vitae placerat
  porta, magna risus euismod purus, in viverra lorem dui at metus. Sed ac sollicitudin nunc. In maximus ipsum nunc,
  placerat maximus tortor gravida varius. Suspendisse pretium, lorem at porttitor rhoncus, nulla urna condimentum
  tortor, sed suscipit nisi metus ac risus.  Aenean sit amet enim quis lorem tristique commodo vitae ut lorem. Duis vel
  tincidunt lacus. Sed massa velit, lacinia sed posuere vitae, malesuada vel ante. Praesent a rhoncus leo. Etiam sed
  rutrum enim. Pellentesque lobortis elementum augue, at suscipit justo malesuada at. Lorem ipsum dolor sit amet,
  consectetur adipiscing elit. Praesent rhoncus convallis ex. Etiam commodo nunc ex, non consequat diam consectetur ut.
  Pellentesque vitae est nec enim interdum dapibus. Donec dapibus purus ipsum, eget tincidunt ex gravida eget. Donec
  luctus nisi eu fringilla mollis. Donec eget lobortis diam.  Suspendisse finibus placerat dolor. Etiam ornare elementum
  ex ut vehicula. Donec accumsan mattis erat. Quisque cursus fringilla diam, eget placerat neque bibendum eu. Ut
  faucibus dui vitae dolor porta, at elementum ipsum semper. Sed ultrices dui non arcu pellentesque placerat. Etiam
  posuere malesuada turpis, nec malesuada tellus malesuada.
acknowledgements: |
  \subsection*{Personal}

  This is where you thank your advisor, colleagues, and family and friends.  Lorem ipsum dolor sit amet, consectetur
  adipiscing elit. Vestibulum feugiat et est at accumsan. Praesent sed elit mattis, congue mi sed, porta ipsum. In non
  ullamcorper lacus. Quisque volutpat tempus ligula ac ultricies. Nam sed erat feugiat, elementum dolor sed, elementum
  neque. Aliquam eu iaculis est, a sollicitudin augue. Cras id lorem vel purus posuere tempor. Proin tincidunt, sapien
  non dictum aliquam, ex odio ornare mauris, ultrices viverra nisi magna in lacus. Fusce aliquet molestie massa, ut
  fringilla purus rutrum consectetur. Nam non nunc tincidunt, rutrum dui sit amet, ornare nunc. Donec cursus tortor vel
  odio molestie dignissim. Vivamus id mi erat. Duis porttitor diam tempor rutrum porttitor. Lorem ipsum dolor sit amet,
  consectetur adipiscing elit. Sed condimentum venenatis consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing
  elit.  Aenean sit amet lectus nec tellus viverra ultrices vitae commodo nunc. Mauris at maximus arcu. Aliquam varius
  congue orci et ultrices. In non ipsum vel est scelerisque efficitur in at augue. Nullam rhoncus orci velit. Duis
  ultricies accumsan feugiat. Etiam consectetur ornare velit et eleifend.  Suspendisse sed enim lacinia, pharetra neque
  ac, ultricies urna. Phasellus sit amet cursus purus. Quisque non odio libero. Etiam iaculis odio a ex volutpat, eget
  pulvinar augue mollis. Mauris nibh lorem, mollis quis semper quis, consequat nec metus. Etiam dolor mi, cursus a ipsum
  aliquam, eleifend venenatis ipsum. Maecenas tempus, nibh eget scelerisque feugiat, leo nibh lobortis diam, id laoreet
  purus dolor eu mauris. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
  Nulla eget tortor eu arcu sagittis euismod fermentum id neque. In sit amet justo ligula. Donec rutrum ex a aliquet
  egestas.

  \subsection*{Institutional}
  If you want to separate out your thanks for funding and institutional support, I don't think there's any rule against
  it.  Of course, you could also just remove the subsections and do one big traditional acknowledgement section.  Lorem
  ipsum dolor sit amet, consectetur adipiscing elit. Ut luctus tempor ex at pretium. Sed varius, mauris at dapibus
  lobortis, elit purus tempor neque, facilisis sollicitudin felis nunc a urna. Morbi mattis ante non augue blandit
  pulvinar. Quisque nec euismod mauris. Nulla et tellus eu nibh auctor malesuada quis imperdiet quam. Sed eget tincidunt
  velit. Cras molestie sem ipsum, at faucibus quam mattis vel. Quisque vel placerat orci, id tempor urna. Vivamus
  mollis, neque in aliquam consequat, dui sem volutpat lorem, sit amet tempor ipsum felis eget ante. Integer lacinia
  nulla vitae felis vulputate, at tincidunt ligula maximus. Aenean venenatis dolor ante, euismod ultrices nibh mollis
  ac. Ut malesuada aliquam urna, ac interdum magna malesuada posuere.

figPrefix:
  - "Figure"
  - "Figures"
eqnPrefix:
  - "Eq."
  - "Eqns."
tblPrefix:
  - "Table"
  - "Tables"
...